import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

// Define the URL mappings for each language
export const urlMappings = {
  'br': {
    'alimento': 'food',
    'calculadora-cientifica': 'scientific-calculator',
    'calculadora-data-de-vencimento': 'due-date-calculator',
    'calculadora-de-acessibilidade-a-habitacao': 'house-affordability-calculator',
    'calculadora-401k': '401k-calculator',
    'calculadora-de-altura': 'height-calculator',
    'calculadora-de-aluguel': 'rent-calculator',
    'calculadora-de-idade': 'age-calculator',
    'calculadora-de-amortizacao': 'amortization-calculator',
    'calculadora-de-anuidades': 'annuity-calculator',
    'calculadora-de-financiamento-de-veiculo': 'auto-loan-calculator',
    'calculadora-de-aposentadoria': 'retirement-calculator',
    'calculadora-de-area-de-superficie-corporal': 'body-surface-area-calculator',
    'calculadora-de-arremesso-independente-de-defesa': 'fielding-independent-pitching-calculator',
    'calculadora-de-bac': 'bac-calculator',
    'Calculadora-de-Biotipo-Corporal': 'body-type-calculator',
    'calculadora-de-imposto-sobre-heranca': 'estate-tax-calculator',
    'calculadora-de-calorias': 'calorie-calculator',
    'calculadora-de-calorias-queimadas': 'calories-burned-calculator',
    'calculadora-de-carboidratos': 'carbohydrate-calculator',
    'calculadora-de-cartao-de-credito': 'credit-card-calculator',
    'calculadora-de-casamento': 'marriage-calculator',
    'calculadora-de-coeficiente-balistico': 'ballistic-coefficient-calculator',
    'calculadora-de-concepcao': 'conception-calculator',
    'calculadora-de-concepcao-de-gravidez': 'pregnancy-conception-calculator',
    'calculadora-de-conservacao-de-momento': 'conservation-of-momentum-calculator',
    'calculadora-de-consumo-de-gordura': 'fat-intake-calculator',
    'calculadora-de-distancia-de-salto-de-carro': 'car-jump-distance-calculator',
    'calculadora-de-emprestimo': 'loan-calculator',
    'calculadora-de-epe': 'rpe-calculator',
    'calculadora-de-erro-percentual': 'percent-error-calculator',
    'calculadora-de-forma-de-bolo': 'cake-pan-calculator',
    'calculadora-de-frequencia-cardiaca-alvo': 'target-heart-rate-calculator',
    'calculadora-de-galoes-por-pe-quadrado': 'gallons-per-square-foot-calculator',
    'calculadora-de-ganho-de-peso-na-gravidez': 'pregnancy-weight-gain-calculator',
    'calculadora-de-gordura-corporal': 'body-fat-calculator',
    'calculadora-de-gordura-corporal-do-exercito': 'army-body-fat-calculator',
    'calculadora-de-gravidez': 'pregnancy-calculator',
    'calculadora-de-imposto-de-renda': 'income-tax-calculator',
    'calculadora-de-inflacao': 'inflation-calculator',
    'calculadora-de-investimentos': 'investment-calculator',
    'calculadora-de-juros': 'interest-calculator',
    'calculadora-de-juros-compostos': 'compound-interest-calculator',
    'calculadora-de-manteiga': 'butter-calculator',
    'calculadora-de-massa-corporal-magra': 'lean-body-mass-calculator',
    'calculadora-de-media-de-corridas-ganhas': 'earned-run-average-calculator',
    'calculadora-de-media-de-rebatidas': 'batting-average-calculator',
    'calculadora-de-metros-cubicos': 'cubic-yard-calculator',
    'calculadora-de-moedas': 'currency-calculator',
    'calculadora-de-ovulacao': 'ovulation-calculator',
    'calculadora-de-pagamento': 'payment-calculator',
    'calculadora-de-pagamento-de-anuidade': 'annuity-payout-calculator',
    'calculadora-de-pe-de-tabua': 'board-foot-calculator',
    'calculadora-de-pensao': 'pension-calculator',
    'calculadora-de-pensao-alimenticia-de-indiana': 'indiana-child-support-calculator',
    'calculadora-de-periodo-fertil': 'period-calculator',
    'calculadora-de-pes-quadrados-para-jardas-cubicas': 'square-feet-to-cubic-yards-calculator',
    'calculadora-de-peso-ideal': 'ideal-weight-calculator',
    'calculadora-de-peso-saudavel': 'healthy-weight-calculator',
    'calculadora-de-ponto-critico': 'critical-point-calculator',
    'calculadora-de-pontos-vigilantes-do-peso': 'weight-watchers-points-calculator',
    'calculadora-de-porcentagem': 'percentage-calculator',
    'calculadora-de-impostos-sobre-vendas': 'sales-tax-calculator',
    'calculadora-de-quitacao-de-dividas': 'debt-payoff-calculator',
    'calculadora-de-quitacao-da-hipoteca': 'mortgage-payoff-calculator',
    'calculadora-de-porcentagem-de-defesa': 'fielding-percentage-calculator',
    'calculadora-de-poupanca': 'savings-calculator',
    'calculadora-de-proteina': 'protein-calculator',
    'calculadora-de-ritmo': 'pace-calculator',
    'calculadora-de-roi-de-seo-empresarial': 'enterprise-seo-roi-calculator',
    'calculadora-de-salario': 'salary-calculator',
    'calculadora-de-sobrepeso': 'overweight-calculator',
    'calculadora-de-tamanho-para-peso-cuboide-retangular': 'size-to-weight-rectangular-cuboid-calculator',
    'calculadora-de-taxa-de-juros': 'interest-rate-calculator',
    'calculadora-de-tempo': 'time-calculator',
    'calculadora-de-uma-repeticao-maxima': 'one-rep-max-calculator',
    'calculadora-de-velocidade': 'velocity-calculator',
    'calculadora-de-velocidade-de-flecha': 'arrow-speed-calculator',
    'calculadora-de-volume': 'volume-calculator',
    'calculadora-desub-rede-IP': 'ip-subnet-calculator',
    'calculadora-do-numero-magico': 'magic-number-calculator',
    'calculadora-gdet': 'tdee-calculator',
    'calculadora-gpa': 'gpa-calculator',
    'calculadora-imc': 'bmi-calculator',
    'calculadora-imc-anorexico': 'anorexic-bmi-calculator',
    'calculadora-macro': 'macro-calculator',
    'calculadora-regra-de-simpson': 'simpsons-rule-calculator',
    'calculadora-teorema-do-valor-medio': 'mean-value-theorem-calculator',
    'calculadora-tfg': 'gfr-calculator',
    'calculadora-tmb': 'bmr-calculator',
    'construcao': 'construction',
    'Conversor-de-Macarrao-Cru-para-Cozido': 'dry-to-cooked-pasta-converter',
    'conversor-de-medidas-culinarias': 'cooking-measurement-converter',
    'calculadora-de-medidas-culinarias': 'cooking-measurement-converter',
    'calculadora-financeira': 'finance-calculator',
    'cups-to-pounds-converter': 'cups-to-pounds-converter',
    'calculadora-de-xicaras-para-libras': 'cups-to-pounds-converter',
    'esportes': 'sports',
    'financeiro': 'financial',
    'fisica': 'physics',
    'gerador-de-numero-aleatorio': 'random-number-generator',
    'matematica': 'maths',
    'outro': 'other-calculators',
    'piecewise-function-calculator-grapher': 'piecewise-function-calculator-grapher',
    'calculadora-de-funcao-por-partes-e-graficador': 'piecewise-function-calculator-grapher',
    'saude': 'health',
    'simulador-da-previdencia': 'social-security-calculator',
    'simulador-de-cartao-de-credito': 'credit-card-payoff-calculator',
    'simulador-hipoteca': 'mortgage-calculator'
  },
  'pl': {
    'kalkulator-szesciennych-jardow': 'cubic-yard-calculator',
    'kalkulator-kredytowy': 'loan-calculator',
    'kalkulator-stezenia-alkoholu-we-krwi': 'bac-calculator',
    'budowa': 'construction',
    'finansowy': 'financial',
    'fizyka': 'physics',
    'inne': 'other-calculators',
    'kalkulator-401-k': '401k-calculator',
    'kalkulator-gfr': 'gfr-calculator',
    'kalkulator-amortyzacji': 'amortization-calculator',
    'kalkulator-annuity-wyplaty-kalkulador': 'annuity-payout-calculator',
    'kalkulator-anorektyczny-bmi-kalkulador': 'anorexic-bmi-calculator',
    'kalkulator-balistyczny-wspolczynnik-kalkulador': 'ballistic-coefficient-calculator',
    'kalkulator-beztluszczowej-ciala-masy-kalkulador': 'lean-body-mass-calculator',
    'kalkulator-bmi': 'bmi-calculator',
    'kalkulator-bmr': 'bmr-calculator',
    'kalkulator-ciasto-patelnia-kalkulador': 'cake-pan-calculator',
    'kalkulator-ciazy': 'pregnancy-calculator',
    'kalkulator-ciazy-poczecia-kalkulador': 'pregnancy-conception-calculator',
    'kalkulator-ciazy-wagi-przyrostu-kalkulador': 'pregnancy-weight-gain-calculator',
    'kalkulator-czasu': 'time-calculator',
    'kalkulator-czynszu': 'rent-calculator',
    'kalkulator-deski-sdopy-kalkulador': 'board-foot-calculator',
    'kalkulator-dlugu-splaty-kalkulador': 'debt-payoff-calculator',
    'kalkulator-docelowego-tetna-czesdotliwosci-kalkulador': 'target-heart-rate-calculator',
    'kalkulator-domu-przystepnosci-kalkulador': 'house-affordability-calculator',
    'kalkulator-dostepnosci-domu': 'house-affordability-calculator',
    'kalkulator-wyplaty-renty': 'annuity-payout-calculator',
    'kalkulator-podatku-vat': 'sales-tax-calculator',
    'kalkulator-emerytalny': 'retirement-calculator',
    'kalkulator-emerytury': 'pension-calculator',
    'kalkulator-finansowy': 'finance-calculator',
    'kalkulator-galony-na-kwadradowy-sdopy-kalkulador': 'gallons-per-square-foot-calculator',
    'kalkulator-gotowanie-pomiar-kalkulador': 'cooking-measurement-converter',
    'kalkulator-idealnej-wagi': 'ideal-weight-calculator',
    'kalkulator-indiana-dziecko-wsparcie-kalkulador': 'indiana-child-support-calculator',
    'kalkulator-inflacji': 'inflation-calculator',
    'kalkulator-inwestycyjny': 'investment-calculator',
    'kalkulator-jednego-rap-kalkulador': 'one-rep-max-calculator',
    'kalkulator-kalorii': 'calorie-calculator',
    'kalkulator-kalorii-spalonych-kalkulador': 'calories-burned-calculator',
    'kalkulator-karty-kredytowej': 'credit-card-calculator',
    'kalkulator-kredytu-hipotecznego': 'mortgage-calculator',
    'kalkulator-kredytu-samochodowego': 'auto-loan-calculator',
    'kalkulator-krytyczny-punkt-kalkulador': 'critical-point-calculator',
    'kalkulator-kubki-do-funty-kalkulador': 'cups-to-pounds-converter',
    'kalkulator-kwadradowy-stopy-do-szescienne-jards-kalkulador': 'square-feet-to-cubic-yards-calculator',
    'kalkulator-losowy-liczba-generador-kalkulador': 'random-number-generator',
    'kalkulator-małżeński': 'marriage-calculator',
    'kalkulator-magiczny-liczba-kalkulador': 'magic-number-calculator',
    'kalkulator-makro': 'macro-calculator',
    'kalkulator-maslo-kalkulador': 'butter-calculator',
    'kalkulator-naukowy': 'scientific-calculator',
    'kalkulator-objetosci': 'volume-calculator',
    'kalkulator-obrona-niezalezny-rzucanie-kalkulador': 'fielding-independent-pitching-calculator',
    'kalkulator-obrona-procendowy-kalkulador': 'fielding-percentage-calculator',
    'kalkulator-odcinkowy-funkcja-kalkulador-wykres-kalkulador': 'piecewise-function-calculator-grapher',
    'kalkulator-odsetek': 'interest-calculator',
    'kalkulator-okresu': 'period-calculator',
    'kalkulator-oszczednosci': 'savings-calculator',
    'kalkulator-overwieght-kalkulador': 'overweight-calculator',
    'kalkulator-owulacji': 'ovulation-calculator',
    'kalkulator-płatności': 'payment-calculator',
    'kalkulator-poczecia': 'conception-calculator',
    'kalkulator-podatku-dochodowego': 'income-tax-calculator',
    'kalkulator-podsieci-ip': 'ip-subnet-calculator',
    'kalkulator-powierzchni-ciala': 'body-surface-area-calculator',
    'kalkulator-predkosci': 'velocity-calculator',
    'kalkulator-procent-bledu-kalkulador': 'percent-error-calculator',
    'kalkulator-procentowy': 'percentage-calculator',
    'kalkulator-procentu-skladanego': 'compound-interest-calculator',
    'kalkulator-protien-spozycia-kalkulador': 'protein-calculator',
    'kalkulator-przedsiebiorstwo-seo-roi-kalkulador': 'enterprise-seo-roi-calculator',
    'kalkulator-renty': 'annuity-calculator',
    'kalkulator-rozmiar-do-wagi-prostokatny-prostopadloscian-kalkulador': 'size-to-weight-rectangular-cuboid-calculator',
    'kalkulator-rpe-kalkulador': 'rpe-calculator',
    'kalkulator-sales-tax-calulcador': 'sales-tax-calculator',
    'kalkulator-samochodu-skoku-odleglosc-kalkulador': 'car-jump-distance-calculator',
    'kalkulator-simpsona-regula-kalkulador': 'simpsons-rule-calculator',
    'kalkulator-splaty-karty-kredytowej': 'credit-card-payoff-calculator',
    'kalkulator-splaty-kredytu-hipotecznego': 'mortgage-payoff-calculator',
    'kalkulator-srednia-wardosc-twierdzenie-kalkulador': 'mean-value-theorem-calculator',
    'kalkulator-sredniej-ocen': 'gpa-calculator',
    'kalkulator-stóp-procentowych': 'interest-rate-calculator',
    'kalkulator-strzaly-predkosc-kalkulador': 'arrow-speed-calculator',
    'kalkulator-suchy-do-gotowany-makaron-kalkulador': 'dry-to-cooked-pasta-converter',
    'kalkulator-tdee': 'tdee-calculator',
    'kalkulator-tempa': 'pace-calculator',
    'kalkulator-terminu-porodu': 'due-date-calculator',
    'kalkulator-tkanki-tluszczowej': 'body-fat-calculator',
    'kalkulator-tluszczu-spozycia-kalkulador': 'fat-intake-calculator',
    'kalkulator-typu-sylwetki': 'body-type-calculator',
    'kalkulator-uderzen-srednia-kalkulador': 'batting-average-calculator',
    'kalkulator-wagi-obserwadorow-punkdow-kalkulador': 'weight-watchers-points-calculator',
    'kalkulator-walutowy': 'currency-calculator',
    'kalkulator-weglowodanow': 'carbohydrate-calculator',
    'kalkulator-wieku': 'age-calculator',
    'kalkulator-wojskowy-ciala-tluszczu-kalkulador': 'army-body-fat-calculator',
    'kalkulator-wynagrodzeń': 'salary-calculator',
    'kalkulator-wzrostu': 'height-calculator',
    'kalkulator-zachowanie-of-pedu-kalkulador': 'conservation-of-momentum-calculator',
    'kalkulator-zdobyty-bieg-srednia-kalkulador': 'earned-run-average-calculator',
    'kalkulator-zdrowej-wagi-kalkulador': 'healthy-weight-calculator',
    'kalkulator-zus': 'social-security-calculator',
    'lekkoatletyka': 'sports',
    'matematyka': 'maths',
    'podatek-od-nieruchomosci-kalkulator': 'estate-tax-calculator',
    'zdrowie': 'health',
    'zywnosc': 'food',
  },
  'de': {
    '401-k-rechner': '401k-calculator',
    'essen': 'food',
    'gesundheit': 'health',
    'konstruktion': 'construction',
    'mathe': 'maths',
    'physik': 'physics',
    'sport': 'sports',
    'alter-rechner': 'age-calculator',
    'andere': 'other-calculators',
    'anorektisch-bmi-rechner': 'anorexic-bmi-calculator',
    'army-korperfettrechner': 'army-body-fat-calculator',
    'autokreditrechner': 'auto-loan-calculator',
    'ballistisch-koeffizient-rechner': 'ballistic-coefficient-calculator',
    'berechnung-der-korperoberflache': 'body-surface-area-calculator',
    'blutalkohol-berechnen': 'bac-calculator',
    'bmi-rechner': 'bmi-calculator',
    'bmr-rechner': 'bmr-calculator',
    'brett-fub-rechner': 'board-foot-calculator',
    'butter-rechner': 'butter-calculator',
    'durchschnittsrechner': 'mean-value-theorem-calculator',
    'ein-rap-rechner': 'one-rep-max-calculator',
    'einkommen-steuer-rechner': 'income-tax-calculator',
    'eisprungrechner': 'ovulation-calculator',
    'empfangnisrechner': 'conception-calculator',
    'entfernungsrechner': 'car-jump-distance-calculator',
    'erbschaftsteuerrechner': 'estate-tax-calculator',
    'erhaltung-of-impuls-rechner': 'conservation-of-momentum-calculator',
    'feld-prozent-rechner': 'fielding-percentage-calculator',
    'feld-unabhangig-werfen-rechner': 'fielding-independent-pitching-calculator',
    'fett-aufnahme-rechner': 'fat-intake-calculator',
    'finanz-rechner': 'finance-calculator',
    'finanziell': 'financial',
    'finanzrechner': 'house-affordability-calculator',
    'fristenrechner': 'due-date-calculator',
    'gallonen-pro-quadrat-fub-rechner': 'gallons-per-square-foot-calculator',
    'gehaltsrechner': 'salary-calculator',
    'geschwindigkeitsrechner': 'velocity-calculator',
    'gesundes-gewicht-rechner': 'healthy-weight-calculator',
    'gfr-rechner': 'gfr-calculator',
    'grobe-to-gewicht-rechteckig-quader-rechner': 'size-to-weight-rectangular-cuboid-calculator',
    'groben-rechner': 'height-calculator',
    'herzfrequenz-rechner': 'target-heart-rate-calculator',
    'hochzeitsrechner': 'marriage-calculator',
    'hypotheken-rechner': 'mortgage-calculator',
    'hypotheken-ruckzahlung-rechner': 'mortgage-payoff-calculator',
    'hypothekenrechner': 'debt-payoff-calculator',
    'schulden-tilgungsrechner': 'debt-payoff-calculator',
    'haus-erschwinglichkeitsrechner': 'house-affordability-calculator',
    'idealgewicht-rechner': 'ideal-weight-calculator',
    'indiana-kind-unterhalt-rechner': 'indiana-child-support-calculator',
    'inflationsrechner': 'inflation-calculator',
    'investitionsrechner': 'investment-calculator',
    'ip-subnetz-rechner': 'ip-subnet-calculator',
    'kalorien-verbrauch-rechner': 'calories-burned-calculator',
    'kalorienrechner': 'calorie-calculator',
    'koch-messung-rechner': 'cooking-measurement-converter',
    'kohlenhydrate-rechner': 'carbohydrate-calculator',
    'korperfettrechner': 'body-fat-calculator',
    'korperform-rechner': 'body-type-calculator',
    'kreditkartenrechner': 'credit-card-calculator',
    'kreditrechner': 'loan-calculator',
    'kritische-Punkte-rechner': 'critical-point-calculator',
    'kubik-yard-rechner': 'cubic-yard-calculator',
    'kuchenform-rechner': 'cake-pan-calculator',
    'magisch-zahl-rechner': 'magic-number-calculator',
    'makro-rechner': 'macro-calculator',
    'malterr-korpro-masse-rechner': 'lean-body-mass-calculator',
    'mietrechner': 'rent-calculator',
    'notendurchschnitt-rechner': 'gpa-calculator',
    'overwieght-rechner': 'overweight-calculator',
    'periodenrechner': 'period-calculator',
    'pfeil-geschwindigkeit-rechner': 'arrow-speed-calculator',
    'protien-aufnahme-rechner': 'protein-calculator',
    'prozent-fehler-rechner': 'percent-error-calculator',
    'prozentrechner': 'percentage-calculator',
    'quadrat-fub-to-kubik-yards-rechner': 'square-feet-to-cubic-yards-calculator',
    'altersrentenrechner': 'retirement-calculator',
    'leibrentenrechner': 'annuity-calculator',
    'pensionsrechner': 'pension-calculator',
    'rentenzahlung': 'annuity-payout-calculator',
    'rpe-rechner': 'rpe-calculator',
    'schlag-durchschnitt-rechner': 'batting-average-calculator',
    'schwangerschaft-empfangnis-rechner': 'pregnancy-conception-calculator',
    'schwangerschaft-gewichtszunahme-rechner': 'pregnancy-weight-gain-calculator',
    'schwangerschaftsrechner': 'pregnancy-calculator',
    'simpsons-regel-rechner': 'simpsons-rule-calculator',
    'sozialversicherungsrechner': 'social-security-calculator',
    'sparrechner': 'savings-calculator',
    'stuckweise-funktion-rechner-grafik-rechner': 'piecewise-function-calculator-grapher',
    'tassen-to-pfund-rechner': 'cups-to-pounds-converter',
    'tdee-rechner': 'tdee-calculator',
    'temporechner': 'pace-calculator',
    'kreditkarten-tilgungsrechner': 'credit-card-payoff-calculator',
    'tilgungsrechner': 'amortization-calculator',
    'trocken-to-gekocht-nudeln-rechner': 'dry-to-cooked-pasta-converter',
    'umsatz-steuer-calulcator-rechner': 'sales-tax-calculator',
    'unternehmen-seo-roi-rechner': 'enterprise-seo-roi-calculator',
    'verdient-lauf-durchschnitt-rechner': 'earned-run-average-calculator',
    'volumenrechner': 'volume-calculator',
    'wahrungsrechner': 'currency-calculator',
    'weight-watchers-punkte-berechnen': 'weight-watchers-points-calculator',
    'wissenschaftlicher-taschenrechner': 'scientific-calculator',
    'zahlungsrechner': 'payment-calculator',
    'zeit-rechner': 'time-calculator',
    'zinseszinsrechner': 'compound-interest-calculator',
    'zinssatzrechner': 'interest-rate-calculator',
    'zinsrechner': 'interest-calculator',
    'zufall-zahl-generator-rechner': 'random-number-generator',
  }
} as const;

// Define reverse mappings for generating hreflang tags
export const reverseUrlMappings = {
    'br': {
    '401k-calculator': 'calculadora-401k',
    'age-calculator': 'calculadora-de-idade',
    'amortization-calculator': 'calculadora-de-amortizacao',
    'annuity-calculator': 'calculadora-de-anuidades',
    'annuity-payout-calculator': 'calculadora-de-pagamento-de-anuidade',
    'anorexic-bmi-calculator': 'calculadora-imc-anorexico',
    'army-body-fat-calculator': 'calculadora-de-gordura-corporal-do-exercito',
    'arrow-speed-calculator': 'calculadora-de-velocidade-de-flecha',
    'auto-loan-calculator': 'calculadora-de-financiamento-de-veiculo',
    'bac-calculator': 'calculadora-de-bac',
    'ballistic-coefficient-calculator': 'calculadora-de-coeficiente-balistico',
    'batting-average-calculator': 'calculadora-de-media-de-rebatidas',
    'bmi-calculator': 'calculadora-imc',
    'bmr-calculator': 'calculadora-tmb',
    'board-foot-calculator': 'calculadora-de-pe-de-tabua',
    'body-fat-calculator': 'calculadora-de-gordura-corporal',
    'body-surface-area-calculator': 'calculadora-de-area-de-superficie-corporal',
    'body-type-calculator': 'Calculadora-de-Biotipo-Corporal',
    'butter-calculator': 'calculadora-de-manteiga',
    'cake-pan-calculator': 'calculadora-de-forma-de-bolo',
    'calorie-calculator': 'calculadora-de-calorias',
    'calories-burned-calculator': 'calculadora-de-calorias-queimadas',
    'car-jump-distance-calculator': 'calculadora-de-distancia-de-salto-de-carro',
    'carbohydrate-calculator': 'calculadora-de-carboidratos',
    'compound-interest-calculator': 'calculadora-de-juros-compostos',
    'conception-calculator': 'calculadora-de-concepcao',
    'conservation-of-momentum-calculator': 'calculadora-de-conservacao-de-momento',
    'construction': 'construcao',
    'cooking-measurement-converter': 'calculadora-de-medidas-culinarias',
    'credit-card-calculator': 'calculadora-de-cartao-de-credito',
    'credit-card-payoff-calculator': 'simulador-de-cartao-de-credito',
    'critical-point-calculator': 'calculadora-de-ponto-critico',
    'cubic-yard-calculator': 'calculadora-de-metros-cubicos',
    'cups-to-pounds-converter': 'calculadora-de-xicaras-para-libras',
    'currency-calculator': 'calculadora-de-moedas',
    'debt-payoff-calculator': 'calculadora-de-quitacao-de-dividas',
    'dry-to-cooked-pasta-converter': 'Conversor-de-Macarrao-Cru-para-Cozido',
    'due-date-calculator': 'calculadora-data-de-vencimento',
    'earned-run-average-calculator': 'calculadora-de-media-de-corridas-ganhas',
    'enterprise-seo-roi-calculator': 'calculadora-de-roi-de-seo-empresarial',
    'estate-tax-calculator': 'calculadora-de-imposto-sobre-heranca',
    'fat-intake-calculator': 'calculadora-de-consumo-de-gordura',
    'fielding-independent-pitching-calculator': 'calculadora-de-arremesso-independente-de-defesa',
    'fielding-percentage-calculator': 'calculadora-de-porcentagem-de-defesa',
    'finance-calculator': 'calculadora-financeira',
    'financial': 'financeiro',
    'food': 'alimento',
    'gallons-per-square-foot-calculator': 'calculadora-de-galoes-por-pe-quadrado',
    'gfr-calculator': 'calculadora-tfg',
    'gpa-calculator': 'calculadora-gpa',
    'health': 'saude',
    'healthy-weight-calculator': 'calculadora-de-peso-saudavel',
    'height-calculator': 'calculadora-de-altura',
    'house-affordability-calculator': 'calculadora-de-acessibilidade-a-habitacao',
    'ideal-weight-calculator': 'calculadora-de-peso-ideal',
    'income-tax-calculator': 'calculadora-de-imposto-de-renda',
    'indiana-child-support-calculator': 'calculadora-de-pensao-alimenticia-de-indiana',
    'inflation-calculator': 'calculadora-de-inflacao',
    'interest-calculator': 'calculadora-de-juros',
    'interest-rate-calculator': 'calculadora-de-taxa-de-juros',
    'investment-calculator': 'calculadora-de-investimentos',
    'ip-subnet-calculator': 'calculadora-desub-rede-IP',
    'lean-body-mass-calculator': 'calculadora-de-massa-corporal-magra',
    'loan-calculator': 'calculadora-de-emprestimo',
    'macro-calculator': 'calculadora-macro',
    'magic-number-calculator': 'calculadora-do-numero-magico',
    'marriage-calculator': 'calculadora-de-casamento',
    'maths': 'matematica',
    'mean-value-theorem-calculator': 'calculadora-teorema-do-valor-medio',
    'mortgage-calculator': 'simulador-hipoteca',
    'mortgage-payoff-calculator': 'calculadora-de-quitacao-da-hipoteca',
    'one-rep-max-calculator': 'calculadora-de-uma-repeticao-maxima',
    'other-calculators': 'outro',
    'overweight-calculator': 'calculadora-de-sobrepeso',
    'ovulation-calculator': 'calculadora-de-ovulacao',
    'pace-calculator': 'calculadora-de-ritmo',
    'payment-calculator': 'calculadora-de-pagamento',
    'pension-calculator': 'calculadora-de-pensao',
    'percent-error-calculator': 'calculadora-de-erro-percentual',
    'percentage-calculator': 'calculadora-de-porcentagem',
    'period-calculator': 'calculadora-de-periodo-fertil',
    'physics': 'fisica',
    'piecewise-function-calculator-grapher': 'calculadora-de-funcao-por-partes-e-graficador',
    'pregnancy-calculator': 'calculadora-de-gravidez',
    'pregnancy-conception-calculator': 'calculadora-de-concepcao-de-gravidez',
    'pregnancy-weight-gain-calculator': 'calculadora-de-ganho-de-peso-na-gravidez',
    'protein-calculator': 'calculadora-de-proteina',
    'random-number-generator': 'gerador-de-numero-aleatorio',
    'rent-calculator': 'calculadora-de-aluguel',
    'retirement-calculator': 'calculadora-de-aposentadoria',
    'rpe-calculator': 'calculadora-de-epe',
    'salary-calculator': 'calculadora-de-salario',
    'sales-tax-calculator': 'calculadora-de-impostos-sobre-vendas',
    'savings-calculator': 'calculadora-de-poupanca',
    'scientific-calculator': 'calculadora-cientifica',
    'simpsons-rule-calculator': 'calculadora-regra-de-simpson',
    'size-to-weight-rectangular-cuboid-calculator': 'calculadora-de-tamanho-para-peso-cuboide-retangular',
    'social-security-calculator': 'simulador-da-previdencia',
    'sports': 'esportes',
    'square-feet-to-cubic-yards-calculator': 'calculadora-de-pes-quadrados-para-jardas-cubicas',
    'target-heart-rate-calculator': 'calculadora-de-frequencia-cardiaca-alvo',
    'tdee-calculator': 'calculadora-gdet',
    'time-calculator': 'calculadora-de-tempo',
    'velocity-calculator': 'calculadora-de-velocidade',
    'volume-calculator': 'calculadora-de-volume',
    'weight-watchers-points-calculator': 'calculadora-de-pontos-vigilantes-do-peso'
  },
  'pl': {
    '401k-calculator': 'kalkulator-401-k',
    'age-calculator': 'kalkulator-wieku',
    'amortization-calculator': 'kalkulator-amortyzacji',
    'annuity-calculator': 'kalkulator-renty',
    'annuity-payout-calculator': 'kalkulator-wyplaty-renty',
    'anorexic-bmi-calculator': 'kalkulator-anorektyczny-bmi-kalkulador',
    'army-body-fat-calculator': 'kalkulator-wojskowy-ciala-tluszczu-kalkulador',
    'arrow-speed-calculator': 'kalkulator-strzaly-predkosc-kalkulador',
    'auto-loan-calculator': 'kalkulator-kredytu-samochodowego',
    'bac-calculator': 'kalkulator-stezenia-alkoholu-we-krwi',
    'ballistic-coefficient-calculator': 'kalkulator-balistyczny-wspolczynnik-kalkulador',
    'batting-average-calculator': 'kalkulator-uderzen-srednia-kalkulador',
    'bmi-calculator': 'kalkulator-bmi',
    'bmr-calculator': 'kalkulator-bmr',
    'board-foot-calculator': 'kalkulator-deski-sdopy-kalkulador',
    'body-fat-calculator': 'kalkulator-tkanki-tluszczowej',
    'body-surface-area-calculator': 'kalkulator-powierzchni-ciala',
    'body-type-calculator': 'kalkulator-typu-sylwetki',
    'butter-calculator': 'kalkulator-maslo-kalkulador',
    'cake-pan-calculator': 'kalkulator-ciasto-patelnia-kalkulador',
    'calories-burned-calculator': 'kalkulator-kalorii-spalonych-kalkulador',
    'calorie-calculator': 'kalkulator-kalorii',
    'car-jump-distance-calculator': 'kalkulator-samochodu-skoku-odleglosc-kalkulador',
    'carbohydrate-calculator': 'kalkulator-weglowodanow',
    'compound-interest-calculator': 'kalkulator-procentu-skladanego',
    'conception-calculator': 'kalkulator-poczecia',
    'conservation-of-momentum-calculator': 'kalkulator-zachowanie-of-pedu-kalkulador',
    'construction': 'budowa',
    'cooking-measurement-converter': 'kalkulator-gotowanie-pomiar-kalkulador',
    'credit-card-calculator': 'kalkulator-karty-kredytowej',
    'credit-card-payoff-calculator': 'kalkulator-splaty-karty-kredytowej',
    'critical-point-calculator': 'kalkulator-krytyczny-punkt-kalkulador',
    'cubic-yard-calculator': 'kalkulator-szesciennych-jardow',
    'cups-to-pounds-converter': 'kalkulator-kubki-do-funty-kalkulador',
    'currency-calculator': 'kalkulator-walutowy',
    'debt-payoff-calculator': 'kalkulator-dlugu-splaty-kalkulador',
    'dry-to-cooked-pasta-converter': 'kalkulator-suchy-do-gotowany-makaron-kalkulador',
    'due-date-calculator': 'kalkulator-terminu-porodu',
    'earned-run-average-calculator': 'kalkulator-zdobyty-bieg-srednia-kalkulador',
    'enterprise-seo-roi-calculator': 'kalkulator-przedsiebiorstwo-seo-roi-kalkulador',
    'estate-tax-calculator': 'podatek-od-nieruchomosci-kalkulator',
    'fat-intake-calculator': 'kalkulator-tluszczu-spozycia-kalkulador',
    'fielding-independent-pitching-calculator': 'kalkulator-obrona-niezalezny-rzucanie-kalkulador',
    'fielding-percentage-calculator': 'kalkulator-obrona-procendowy-kalkulador',
    'finance-calculator': 'kalkulator-finansowy',
    'financial': 'finansowy',
    'food': 'zywnosc',
    'gallons-per-square-foot-calculator': 'kalkulator-galony-na-kwadradowy-sdopy-kalkulador',
    'gfr-calculator': 'kalkulator-gfr',
    'gpa-calculator': 'kalkulator-sredniej-ocen',
    'health': 'zdrowie',
    'healthy-weight-calculator': 'kalkulator-zdrowej-wagi-kalkulador',
    'height-calculator': 'kalkulator-wzrostu',
    'house-affordability-calculator': 'kalkulator-dostepnosci-domu',
    'ideal-weight-calculator': 'kalkulator-idealnej-wagi',
    'income-tax-calculator': 'kalkulator-podatku-dochodowego',
    'indiana-child-support-calculator': 'kalkulator-indiana-dziecko-wsparcie-kalkulador',
    'inflation-calculator': 'kalkulator-inflacji',
    'interest-calculator': 'kalkulator-odsetek',
    'interest-rate-calculator': 'kalkulator-stóp-procentowych',
    'investment-calculator': 'kalkulator-inwestycyjny',
    'ip-subnet-calculator': 'kalkulator-podsieci-ip',
    'lean-body-mass-calculator': 'kalkulator-beztluszczowej-ciala-masy-kalkulador',
    'loan-calculator': 'kalkulator-kredytowy',
    'macro-calculator': 'kalkulator-makro',
    'magic-number-calculator': 'kalkulator-magiczny-liczba-kalkulador',
    'marriage-calculator': 'kalkulator-małżeński',
    'maths': 'matematyka',
    'mean-value-theorem-calculator': 'kalkulator-srednia-wardosc-twierdzenie-kalkulador',
    'mortgage-calculator': 'kalkulator-kredytu-hipotecznego',
    'mortgage-payoff-calculator': 'kalkulator-splaty-kredytu-hipotecznego',
    'one-rep-max-calculator': 'kalkulator-jednego-rap-kalkulador',
    'other-calculators': 'inny',
    'overweight-calculator': 'kalkulator-overwieght-kalkulador',
    'ovulation-calculator': 'kalkulator-owulacji',
    'pace-calculator': 'kalkulator-tempa',
    'payment-calculator': 'kalkulator-płatności',
    'pension-calculator': 'kalkulator-emerytury',
    'percent-error-calculator': 'kalkulator-procent-bledu-kalkulador',
    'percentage-calculator': 'kalkulator-procentowy',
    'period-calculator': 'kalkulator-okresu',
    'physics': 'fizyka',
    'piecewise-function-calculator-grapher': 'kalkulator-odcinkowy-funkcja-kalkulador-wykres-kalkulador',
    'pregnancy-calculator': 'kalkulator-ciazy',
    'pregnancy-conception-calculator': 'kalkulator-ciazy-poczecia-kalkulador',
    'pregnancy-weight-gain-calculator': 'kalkulator-ciazy-wagi-przyrostu-kalkulador',
    'protein-calculator': 'kalkulator-protien-spozycia-kalkulador',
    'random-number-generator': 'kalkulator-losowy-liczba-generador-kalkulador',
    'rent-calculator': 'kalkulator-czynszu',
    'retirement-calculator': 'kalkulator-emerytalny',
    'rpe-calculator': 'kalkulator-rpe-kalkulador',
    'salary-calculator': 'kalkulator-wynagrodzeń',
    'sales-tax-calculator': 'kalkulator-podatku-vat',
    'savings-calculator': 'kalkulator-oszczednosci',
    'scientific-calculator': 'kalkulator-naukowy',
    'simpsons-rule-calculator': 'kalkulator-simpsona-regula-kalkulador',
    'size-to-weight-rectangular-cuboid-calculator': 'kalkulator-rozmiar-do-wagi-prostokatny-prostopadloscian-kalkulador',
    'social-security-calculator': 'kalkulator-zus',
    'sports': 'lekkoatletyka',
    'square-feet-to-cubic-yards-calculator': 'kalkulator-kwadradowy-stopy-do-szescienne-jards-kalkulador',
    'target-heart-rate-calculator': 'kalkulator-docelowego-tetna-czesdotliwosci-kalkulador',
    'tdee-calculator': 'kalkulator-tdee',
    'time-calculator': 'kalkulator-czasu',
    'velocity-calculator': 'kalkulator-predkosci',
    'volume-calculator': 'kalkulator-objetosci',
    'weight-watchers-points-calculator': 'kalkulator-wagi-obserwadorow-punkdow-kalkulador',
  },
  'de': {
    '401k-calculator': '401-k-rechner',
    'age-calculator': 'alter-rechner',
    'amortization-calculator': 'tilgungsrechner',
    'annuity-calculator': 'leibrentenrechner',
    'annuity-payout-calculator': 'rentenzahlung',
    'anorexic-bmi-calculator': 'anorektisch-bmi-rechner',
    'army-body-fat-calculator': 'army-korperfettrechner',
    'arrow-speed-calculator': 'pfeil-geschwindigkeit-rechner',
    'auto-loan-calculator': 'autokreditrechner',
    'bac-calculator': 'blutalkohol-berechnen',
    'ballistic-coefficient-calculator': 'ballistisch-koeffizient-rechner',
    'batting-average-calculator': 'schlag-durchschnitt-rechner',
    'bmi-calculator': 'bmi-rechner',
    'bmr-calculator': 'bmr-rechner',
    'board-foot-calculator': 'brett-fub-rechner',
    'body-fat-calculator': 'korperfettrechner',
    'body-surface-area-calculator': 'berechnung-der-korperoberflache',
    'body-type-calculator': 'korperform-rechner',
    'butter-calculator': 'butter-rechner',
    'cake-pan-calculator': 'kuchenform-rechner',
    'calories-burned-calculator': 'kalorien-verbrauch-rechner',
    'calorie-calculator': 'kalorienrechner',
    'car-jump-distance-calculator': 'entfernungsrechner',
    'carbohydrate-calculator': 'kohlenhydrate-rechner',
    'compound-interest-calculator': 'zinseszinsrechner',
    'conception-calculator': 'empfangnisrechner',
    'conservation-of-momentum-calculator': 'erhaltung-of-impuls-rechner',
    'construction': 'konstruktion',
    'cooking-measurement-converter': 'koch-messung-rechner',
    'credit-card-calculator': 'kreditkartenrechner',
    'credit-card-payoff-calculator': 'kreditkarten-tilgungsrechner',
    'critical-point-calculator': 'kritische-Punkte-rechner',
    'cubic-yard-calculator': 'kubik-yard-rechner',
    'cups-to-pounds-converter': 'tassen-to-pfund-rechner',
    'currency-calculator': 'wahrungsrechner',
    'debt-payoff-calculator': 'schulden-tilgungsrechner',
    'dry-to-cooked-pasta-converter': 'trocken-to-gekocht-nudeln-rechner',
    'due-date-calculator': 'fristenrechner',
    'earned-run-average-calculator': 'verdient-lauf-durchschnitt-rechner',
    'enterprise-seo-roi-calculator': 'unternehmen-seo-roi-rechner',
    'estate-tax-calculator': 'erbschaftsteuerrechner',
    'fat-intake-calculator': 'fett-aufnahme-rechner',
    'fielding-independent-pitching-calculator': 'feld-unabhangig-werfen-rechner',
    'fielding-percentage-calculator': 'feld-prozent-rechner',
    'finance-calculator': 'finanz-rechner',
    'financial': 'finanziell',
    'food': 'essen',
    'gallons-per-square-foot-calculator': 'gallonen-pro-quadrat-fub-rechner',
    'gfr-calculator': 'gfr-rechner',
    'gpa-calculator': 'notendurchschnitt-rechner',
    'health': 'gesundheit',
    'healthy-weight-calculator': 'gesundes-gewicht-rechner',
    'height-calculator': 'groben-rechner',
    'house-affordability-calculator': 'haus-erschwinglichkeitsrechner',
    'ideal-weight-calculator': 'idealgewicht-rechner',
    'income-tax-calculator': 'einkommen-steuer-rechner',
    'indiana-child-support-calculator': 'indiana-kind-unterhalt-rechner',
    'inflation-calculator': 'inflationsrechner',
    'interest-calculator': 'zinsrechner',
    'interest-rate-calculator': 'zinssatzrechner',
    'investment-calculator': 'investitionsrechner',
    'ip-subnet-calculator': 'ip-subnetz-rechner',
    'lean-body-mass-calculator': 'malterr-korpro-masse-rechner',
    'loan-calculator': 'kreditrechner',
    'macro-calculator': 'makro-rechner',
    'magic-number-calculator': 'magisch-zahl-rechner',
    'marriage-calculator': 'hochzeitsrechner',
    'maths': 'mathe',
    'mean-value-theorem-calculator': 'durchschnittsrechner',
    'mortgage-calculator': 'hypotheken-rechner',
    'mortgage-payoff-calculator': 'hypotheken-ruckzahlung-rechner',
    'one-rep-max-calculator': 'ein-rap-rechner',
    'other-calculators': 'andere',
    'overweight-calculator': 'overwieght-rechner',
    'ovulation-calculator': 'eisprungrechner',
    'pace-calculator': 'temporechner',
    'payment-calculator': 'zahlungsrechner',
    'pension-calculator': 'pensionsrechner',
    'percent-error-calculator': 'prozent-fehler-rechner',
    'percentage-calculator': 'prozentrechner',
    'period-calculator': 'periodenrechner',
    'physics': 'physik',
    'piecewise-function-calculator-grapher': 'stuckweise-funktion-rechner-grafik-rechner',
    'pregnancy-calculator': 'schwangerschaftsrechner',
    'pregnancy-conception-calculator': 'schwangerschaft-empfangnis-rechner',
    'pregnancy-weight-gain-calculator': 'schwangerschaft-gewichtszunahme-rechner',
    'protein-calculator': 'protien-aufnahme-rechner',
    'random-number-generator': 'zufall-zahl-generator-rechner',
    'rent-calculator': 'mietrechner',
    'retirement-calculator': 'altersrentenrechner',
    'rpe-calculator': 'rpe-rechner',
    'salary-calculator': 'gehaltsrechner',
    'sales-tax-calculator': 'umsatz-steuer-calulcator-rechner',
    'savings-calculator': 'sparrechner',
    'scientific-calculator': 'wissenschaftlicher-taschenrechner',
    'simpsons-rule-calculator': 'simpsons-regel-rechner',
    'size-to-weight-rectangular-cuboid-calculator': 'grobe-to-gewicht-rechteckig-quader-rechner',
    'social-security-calculator': 'sozialversicherungsrechner',
    'sports': 'sport',
    'square-feet-to-cubic-yards-calculator': 'quadrat-fub-to-kubik-yards-rechner',
    'target-heart-rate-calculator': 'herzfrequenz-rechner',
    'tdee-calculator': 'tdee-rechner',
    'time-calculator': 'zeit-rechner',
    'velocity-calculator': 'geschwindigkeitsrechner',
    'volume-calculator': 'volumenrechner',
    'weight-watchers-points-calculator': 'weight-watchers-punkte-berechnen',
  }
} as const;

// Define static pages that should keep English URLs but serve localized content
const staticPages = [
  'about-us',
  'contact-us',
  'privacy-policy',
  'terms-and-conditions'
];

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;
  
  // Skip middleware for static files, API routes, and Next.js internals
  if (
    pathname.includes('.') || // static files
    pathname.includes('_next') || // Next.js internals
    pathname.includes('api') || // API routes
    pathname.includes('favicon') // favicon
  ) {
    return NextResponse.next();
  }
  
  // Check if the URL starts with a language prefix
  const langMatch = pathname.match(/^\/(br|pl|de)(\/.*)?/);
  
  if (langMatch) {
    const lang = langMatch[1] as keyof typeof urlMappings;
    const path = langMatch[2] || '/';
    
    // Handle root path for language - show homepage instead of redirecting to calculator
    if (path === '/') {
      // Rewrite to the homepage with language header
      const response = NextResponse.rewrite(new URL('/', request.url));
      response.headers.set('x-language', lang);
      return response;
    }
    
    // Remove the leading slash for processing
    const pathParts = path.substring(1).split('/');
    
    // Check if this is a static page (first part is a static page name)
    const firstPart = pathParts[0];
    if (staticPages.includes(firstPart)) {
      // For static pages, keep the English URL but set the language header
      // We need to rewrite to the English path
      const newPath = '/' + pathParts.join('/');
      const response = NextResponse.rewrite(new URL(newPath, request.url));
      response.headers.set('x-language', lang);
      return response;
    }
    
    // Check if this is a translated static page
    // For example, /br/sobre-nos should rewrite to /about-us
    const translatedStaticPages: Record<string, string> = {
      // Portuguese
      'sobre-nos': 'about-us',
      'contate-nos': 'contact-us',
      'politica-de-privacidade': 'privacy-policy',
      'termos-e-condicoes': 'terms-and-conditions',
      // Polish
      'o-nas': 'about-us',
      'kontakt': 'contact-us',
      'polityka-prywatnosci': 'privacy-policy',
      'regulamin': 'terms-and-conditions',
      // German
      'uber-uns': 'about-us',
      'datenschutz': 'privacy-policy',
      'allgemeine-geschaftsbedingungen': 'terms-and-conditions'
    };
    
    if (translatedStaticPages[firstPart]) {
      // Rewrite to the English version of the static page
      const englishPage = translatedStaticPages[firstPart];
      const newPath = '/' + [englishPage, ...pathParts.slice(1)].join('/');
      const response = NextResponse.rewrite(new URL(newPath, request.url));
      response.headers.set('x-language', lang);
      return response;
    }
    
    // Translate the path parts for non-static pages
    const translatedParts = pathParts.map(part => {
      return urlMappings[lang]?.[part as keyof typeof urlMappings[typeof lang]] || part;
    });
    
    // Construct the new path
    const newPath = '/' + translatedParts.join('/');
    
    // Rewrite to the English version
    const response = NextResponse.rewrite(new URL(newPath, request.url));
    
    // Add language information to headers
    response.headers.set('x-language', lang);
    
    return response;
  }
  
  // For English URLs (no prefix), set language to 'en'
  const response = NextResponse.next();
  response.headers.set('x-language', 'en');
  return response;
}

// Configure which paths the middleware should run on
export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - api (API routes)
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     */
    '/((?!api|_next/static|_next/image|favicon.ico).*)',
  ],
};